"""Emit the study's experiment configs, one file per (arm, condition).

The study is a grid: each defence arm is run under both system-prompt
conditions, on the reportable splits only. Writing the grid out rather than
hand-maintaining fourteen near-identical YAML files is what keeps the arms
actually comparable -- a hand-edited seed, split list or classifier alias in
one file would silently make that arm answer a different question.

Idempotent: rerunning overwrites the files with the same content, so adding
an arm here and rerunning leaves the existing runs' markers untouched and
the driver picks up only what is new.
"""

from pathlib import Path

OUT = Path("experiments/study")
DATASET = "data/generated/tipguard-v1.jsonl"

#: Only the splits a result may be reported on. `train` and `dev` exist for
#: tuning, so measuring on them would report performance on data the defences
#: were fitted to.
SPLITS = "[test, heldout_transformation, heldout_policy, heldout_paraphrase, heldout_compositional]"

HEADER = (
    "# Generated by scripts/write_study_configs.py -- do not hand-edit.\n"
    "# One arm, one system-prompt condition, on the reportable splits.\n"
)

#: `(stem, defense name, params, main model alias)`.
#:
#: `input_classifier` appears twice, under two risk prompts. v1 asks the
#: model to rate an attempt to "extract, encode, or otherwise exfiltrate", so
#: the encoding itself reads as risk and the arm blocks benign transformations
#: at nearly the rate it blocks attacks -- it has no usable operating point.
#: That is a finding about naive LLM filtering rather than a bug to edit
#: away, so v1 is kept and v2 runs beside it as the calibrated baseline the
#: defence is actually measured against.
ARMS: tuple[tuple[str, str, dict[str, str], str], ...] = (
    ("no_defense", "no_defense", {}, "gpt-4o-mini"),
    ("keyword_filter", "keyword_filter", {}, "gpt-4o-mini"),
    ("pattern_detector", "pattern_detector", {}, "gpt-4o-mini"),
    ("input_classifier", "input_classifier", {"classifier_model": "gpt-4o-mini"}, "gpt-4o-mini"),
    (
        "input_classifier_v2",
        "input_classifier",
        {"classifier_model": "gpt-4o-mini", "prompt_version": "risk-v2"},
        "gpt-4o-mini",
    ),
    (
        "input_output_classifier",
        "input_output_classifier",
        {"classifier_model": "gpt-4o-mini"},
        "gpt-4o-mini",
    ),
    (
        "tip_guard",
        "tip_guard",
        {
            "classifier_model": "gpt-4o-mini",
            "canonicalizer_model": "gpt-4o-mini",
            "prompt_version": "risk-v2",
        },
        "gpt-4o-mini",
    ),
    # The isolation arm. `tip_guard` differs from `input_classifier_v2` in
    # three ways at once -- canonicalization, a second input-side classifier,
    # and an output guard -- so that pair cannot attribute a difference to
    # canonicalization. This arm is `tip_guard` with the decoders and the LLM
    # canonicalizer switched off and everything else identical, so the pair
    # `tip_guard` / `tip_guard_no_canon` differs in canonicalization alone.
    (
        "tip_guard_no_canon",
        "tip_guard",
        {
            "classifier_model": "gpt-4o-mini",
            "canonicalizer_model": "gpt-4o-mini",
            "prompt_version": "risk-v2",
            "enable_decoders": "false",
            "enable_llm_canonicalizer": "false",
        },
        "gpt-4o-mini",
    ),
    # The cross-model row: the undefended arm on a second model, because the
    # pilot showed vulnerability is model-dependent and a single-model result
    # would read as a property of the attack rather than of the deployment.
    ("no_defense-haiku", "no_defense", {}, "claude-haiku-4-5"),
)

CONDITIONS = ("context", "forbidden")


def render(stem: str, defense: str, params: dict[str, str], model: str, condition: str) -> str:
    lines = [
        HEADER,
        f"name: {stem.removesuffix('-haiku')}-{condition}-{model}\n",
        "seed: 0\n",
        f"dataset: {DATASET}\n",
        f"main_model: {model}\n",
        f"system_prompt: {condition}\n",
        "defense:\n",
        f"  name: {defense}\n",
    ]
    if params:
        lines.append("  params:\n")
        lines.extend(f"    {key}: {value}\n" for key, value in params.items())
    lines.append(f"splits: {SPLITS}\n")
    lines.append("output_dir: reports/runs\n")
    lines.append("cache_dir: .tipguard-cache\n")
    return "".join(lines)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    written = 0
    for stem, defense, params, model in ARMS:
        for condition in CONDITIONS:
            base = stem.removesuffix("-haiku")
            suffix = "-haiku" if stem.endswith("-haiku") else ""
            path = OUT / f"{base}-{condition}{suffix}.yaml"
            path.write_text(render(stem, defense, params, model, condition), encoding="utf-8")
            written += 1
    print(f"wrote {written} configs to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
